import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Paul Website",
  description: "Generated by create next app",
};

//LoaderContextProvider
import LoaderContextProvider from "../context/LoaderContextProvider";

//Components
import Header from "@/components/Header";
import BurgetMenu from "@/components/BurgerMenu";
import Loader from "@/components/Loader";
import MobileNav from "@/components/MobileNav";
import Spinner from "@/components/Spinner";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LoaderContextProvider>
          <Header />
          {children}
          <BurgetMenu />
          <MobileNav />
          <Loader />
          <Spinner />
        </LoaderContextProvider>
      </body>
    </html>
  );
}
