"use client";
import { useEffect, useRef, Suspense, useState } from "react";

import loaderStyle from "./../styles/modules/loader.module.scss";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.scss";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

//Components
import Header from "@/components/Header";
import Flashlight from "@/components/Flashlight";
import BurgetMenu from "@/components/BurgerMenu";
import Loader from "@/components/Loader";

//scripts
import flashlightEffect from "@/scripts/flashlightEffect";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isLoading, setIsLoading] = useState(true);
  const loaderRef = useRef(null);
  // const flashlightRef = useRef(null);
  useEffect(() => {
    const loaderNode: HTMLDivElement = loaderRef.current!;
    loaderNode.classList.add(loaderStyle.hide);
    setTimeout(() => {
      setIsLoading(false);
    }, 550);
    // const flashlightNode: unknown = flashlightRef.current;
    // flashlightEffect(flashlightNode as HTMLDivElement);
  }, []);
  return (
    <html lang="en">
      <body className={inter.className}>
        {isLoading ? (
          <Loader loaderRef={loaderRef} />
        ) : (
          <>
            <Header />
            {children}
            {/* <Flashlight node={flashlightRef} /> */}
            <BurgetMenu />
          </>
        )}
      </body>
    </html>
  );
}
